version: '3.4'

volumes:
  dbdata:
    driver: local

services:
  db:
    image: postgres:9.4.10-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data:rw

  cf:
    build:
      context: .
      target: development
    image: cf-development
    environment:
      - DOCKER_ENV=1
      - RAILS_ENV
    stdin_open: true
    tty: true
    entrypoint: 
      - scripts/entrypoint
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/app:delegated
    depends_on:
      - db